### ISSUE TITLE
vpnclient is failing to launch

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/vpn#3]
it is existing with error 5, complaining about no trustca.pem.

So apparently, this line : https://github.com/mF2C/mF2C/blob/master/docker-compose/tests/identification-FullAgent.sh#L40

is not working.

```
vpnclient_1                | PING vpnserver (213.205.14.13): 56 data bytes
vpnclient_1                | 64 bytes from 213.205.14.13: seq=0 ttl=51 time=50.174 ms
vpnclient_1                | 
vpnclient_1                | --- vpnserver ping statistics ---
vpnclient_1                | 1 packets transmitted, 1 packets received, 0% packet loss
vpnclient_1                | round-trip min/avg/max = 50.174/50.174/50.174 ms
vpnclient_1                | server.crt: OK
vpnclient_1                | RSA key ok
vpnclient_1                | writing RSA key
vpnclient_1                | Files pubkey1.pem and pubkey2.pem are identical
vpnclient_1                | INFO Credentials checks passed, creating OVPN
vpnclient_1                | INFO OVPN created; launching client
vpnclient_1                | FATAL failed to launch VPN client
mf2c_vpnclient_1 exited with code 5
```

**Comment by jjensenral** [comment]
I know why this is - the trust anchor is only installed by the client when it recreates the credential. (In theory the client should NEVER install its own trust anchors but it has the faciility to do so.) 
This is fixed in the ARM version of 1.1.2. Should I rebuild the PC image or update the version number?
( a workaround is to install trustca.pem by hand into the volume)

**Comment by jjensenral** [comment]
OK, in the interest of time, I have pushed an updated image mf2c/vpnclient:1.1.2 (and tested it). It now acts like the ARM version, always recreating trustca if it's missing.

**Comment by jjensenral** [comment]
In my tests, it is fixed. You might need to delete your mf2c/vpnclient:1.1.2 and have it re-download.
