### ISSUE TITLE
Bad JSON formatting when VPN is not established

### ISSUE THREAD

**Issue by ALEJANDROJ19** [mF2C/vpn#4]
I just detected that when the vpn-client is not connected to the vpn server, the JSON stored at the volume does not match with a valid JSON.

Output:
```
{"status":"waiting for cred","ip":"","server":"","lastUpdate":"20191015 14:57:11+0000","stats":,"msg":""}
```

Validator Output
```
Error:Expecting value, not comma.[Code 9, Structure 19]
"stats":,
```

needed in: https://github.com/mF2C/ResourceManagement/issues/58

**Comment by jjensenral** [comment]
ooh you're right; well spotted. Will fix.
